# Use an official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /usr/src/app
COPY . .



# Make port 80 available to the world outside this container
EXPOSE 80
